services:
  app:
    image: notifications-bot
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./:/app
      - ./notifications-bot-db:/notifications-bot-db
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - TELEGRAM_BOT_API_TOKEN=${TELEGRAM_BOT_API_TOKEN}
      - NOTIFICATION_SECRET=${NOTIFICATION_SECRET}
      - DB_FOLDER=/notifications-bot-db
      - IS_PRIVATE=${IS_PRIVATE}