version: '3'

services:
  myapp:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:${DOCKER_TAG}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./volumes:/volumes
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - TELEGRAM_BOT_API_TOKEN=${TELEGRAM_BOT_API_TOKEN}
      - NOTIFICATION_SECRET=${NOTIFICATION_SECRET}
